# Generated by Django 4.0 on 2022-11-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_add_date_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
