# Generated by Django 4.0 on 2022-09-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
