# Generated by Django 4.0 on 2022-09-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_contactus_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='firstName',
            new_name='fullname',
        ),
    ]
